name: Audit
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Audit
        run: npm audit --omit=dev
