name: Publish to NPM
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Set version
        run: npm version ${{ github.ref_name }} --no-git-tag-version
      - name: Publish
        run: |
          if [[ ${{ github.ref_name }} == *"beta"* ]]; then
            npm publish --tag beta
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
