name: Publish to NPM
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Set version
        run: npm version ${{ github.ref_name }} --no-git-tag-version
      - name: Publish
        run: |
          if [[ ${{ github.ref_name }} == *"beta"* ]]; then
            npm publish --tag beta --provenance
          else
            npm publish --provenance
          fi
